### ISSUE TITLE
构建出现了俩JAR

### ISSUE THREAD

**Issue by Leoparking** [HaHaWTH/ClientBoomer#2]
<img width="563" alt="image" src="https://github.com/HaHaWTH/ClientBoomer/assets/141799770/3c5a9de6-54e8-46f3-82ec-bb9acc25885a">
一个大一个小，不过两个都带有插件的特征（如plugin.yml和config.yml）
小的那个original-ClientBoomer-PacketEvents-1.2没assets
用途有什么不同吗

**Comment by HaHaWTH** [comment]
用不带original的就可以
